[workspace]
resolver = "2"

members = [ "fft",
    "polynomial",
    "stat",
    "sumcheck",
    "transcript",
]

[workspace.dependencies]
criterion = "0.5.1"
field-tracker = { git = "https://github.com/sublinearlabs/field-tracker" }
